import Head from 'next/head'
import {Navbar} from "@/components/landing/Navbar/Navbar";
import {Hero} from "@/components/landing/Hero/Hero";
import {Footer} from "@/components/landing/Footer/Footer";



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar/>
      <Hero/>
      <Footer/>

    </>
  )
}
