import Head from "next/head";
import Footer from "@/components/landing/Footer/Footer";
import Hero from "@/components/landing/Hero/Hero";
import dynamic from "next/dynamic";
import { NextApiRequest, NextApiResponse } from "next";
import { links } from "@/components/landing/Navbar/links";

const Cookies = require("cookies");
const jwt = require("jsonwebtoken");

const Navbar = dynamic(() => import("../components/landing/Navbar/Navbar"), {
  ssr: false,
});

export default function Home({ loggedIn }: { loggedIn: boolean }) {
  return (
    <>
      <Head>
        <title>Course Seeker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/School_Logo.svg" />
      </Head>

      <Navbar landing loggedIn={loggedIn} links={links} />
      <Hero />
      <Footer />
    </>
  );
}
export async function getServerSideProps({
  req,
  res,
}: {
  req: NextApiRequest;
  res: NextApiResponse;
}) {
  const cookies = new Cookies(req, res);
  const token = cookies.get("token");
  if (!!token) {
    return {
      props: { loggedIn: true },
    };
  } else
    return {
      props: { loggedIn: false },
    };
}
