import React from "react";
import LogIn from "@/components/SignUp-Login/Login/Login";
import { NextApiRequest, NextApiResponse } from "next";
import Navbar from "@/components/SignUp-Login/navbar";
import Head from "next/head";

const Cookies = require("cookies");

const Login = () => {
  return (
    <>
      <Head>
        <title>Course Seeker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/School_Logo.png" />
      </Head>
      <Navbar Login />
      <LogIn />
    </>
  );
};

export default Login;

export async function getServerSideProps({
  req,
  res,
}: {
  req: NextApiRequest;
  res: NextApiResponse;
}) {
  const cookie = new Cookies(req, res);
  const token = cookie.get("token");

  if (token === "" || !token)
    return {
      props: {},
    };

  return {
    redirect: {
      permanent: false,
      destination: "/",
    },
  };
}
